spring.application.name=elearing-backend-service
logging.level.org.springframework.security=DEBUG
logging.level.com.doanptit.elearing_backend_service=DEBUG
spring.profiles.active=local
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173