app.aws.dynamodb.endpoint=http://localhost:4577
app.aws.dynamodb.blacklist-table-name=JwtBlacklist
app.aws.region=us-east-1

# S3 MinIO (LocalStack S3 does not support persistence in Community Edition)
app.aws.s3.bucket=user-images
app.aws.s3.endpoint=http://localhost:9000
app.aws.access-key=minioadmin
app.aws.secret-key=minioadmin