spring.application.name=elearing-backend-service
logging.level.org.springframework.security=DEBUG
logging.level.com.doanptit.elearing_backend_service=DEBUG
spring.profiles.active=local
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
logging.level.org.springframework.web.multipart=DEBUG
logging.level.org.apache.tomcat.util.http.fileupload=DEBUG

spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.embedding.enabled=false
spring.ai.embedding.transformer.enabled=true
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.dimension=384

spring.data.redis.host=localhost
spring.data.redis.port=6379