app.aws.dynamodb.endpoint=http://localhost:4577
app.aws.dynamodb.blacklist-table-name=JwtBlacklist
app.aws.region=us-east-1

# S3 LocalStack
app.aws.s3.bucket=user-images
app.aws.s3.endpoint=http://localhost:4577
app.aws.access-key=test
app.aws.secret-key=test