spring:
  application:
    name: elearning-backend-service

  datasource:
    url: jdbc:postgresql://localhost:5436/elearing-backend-service?sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: elearningservice
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha

  jwt:
    secret: "${JWT_SECRET:defaultSecretKey123456789012345678901234567890}"
    expiration: 86400000

  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: hvmhieu2003@gmail.com
      password: vbun wqya sdkd lomv
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

