package com.doanptit.elearing_backend_service.enums;

public enum CourseCategory {
    ARTIFICIAL_INTELLIGENCE_OF_THINGS,
    INFORMATION_TECHNOLOGY,
    ARTIFICIAL_INTELLIGENCE,
    GAME_DESIGN_AND_DEVELOPMENT,
    MULTIMEDIA_COMMUNICATION,
    ELECTRONICS_AND_TELECOMMUNICATION_ENGINEERING,
    INFORMATION_SECURITY,
    ELECTRICAL_AND_ELECTRONIC_ENGINEERING_TECHNOLOGY,
    MULTIMEDIA_TECHNOLOGY,
    MARKETING,
    BUSINESS_ADMINISTRATION,
    ACCOUNTING,
    E_COMMERCE,
    FINANCIAL_TECHNOLOGY,
    CONTROL_AND_AUTOMATION_ENGINEERING,
    COMPUTER_SCIENCE,
    JOURNALISM,
    COMPUTER_NETWORKS_AND_DATA_COMMUNICATIONS,
    PUBLIC_RELATIONS,
    SEMICONDUCTOR_MICROELECTRONICS_TECHNOLOGY,
    LOGISTICS_AND_SUPPLY_CHAIN_MANAGEMENT
}
