CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               recipient_id VARCHAR(255) NOT NULL,
                               title VARCHAR(255),
                               message TEXT,
                               target_url VARCHAR(500),
                               is_read BOOLEAN DEFAULT FALSE NOT NULL,
                               created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE INDEX idx_notifications_recipient_created
    ON notifications(recipient_id, created_at DESC);